### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by fghjk455rg** [liplum/CyberIO#39]
![image](https://user-images.githubusercontent.com/72150108/211140430-df8d3f39-9a22-4784-8eeb-58511109a2bc.png)

**Comment by liplum** [comment]
What's going on? Please add more details about the bug.

**Comment by fghjk455rg** [comment]
I fix image

**Comment by liplum** [comment]
> I fix image

Alright, please describe what the image means.

**Comment by fghjk455rg** [comment]
This is the Erekir version, but resources with Serpulo.

**Comment by liplum** [comment]
> This is the Erekir version, but resources with Serpulo.

Could you provide more details about your game version？
By the way, I can see the color scheme of IC is for Erekir. So you must switch to CyberIO-Erekir. Do they really cost Serpulor items?

**Comment by fghjk455rg** [comment]
![image](https://user-images.githubusercontent.com/72150108/211145267-9ae6772f-dacf-4fb7-890f-fc45f5956714.png)
No, the cost of items from the Erekir. But the resources are taken from the Serpulo (upper left corner).

**Comment by Phoenixwolf1245** [comment]
It shows the total amount of resources on any planet in your research thing whatever tab you click on and whatever Planet you're on

**Comment by fghjk455rg** [comment]
No, only serpulo

**Comment by Phoenixwolf1245** [comment]
?

**Comment by liplum** [comment]
I got it. It's because Anuke added a field, `planet`, to bind a techtree with a planet. And as default, the `planet` is Serpulo.
So as you seen, Cyber IO's techtree is associated with only Serpulo, not Erekir.
Don't worry, I will fix it soon.

see [the source code](https://github.com/Anuken/Mindustry/blob/f46a9730a3b637602ee706c1d04f23185630860b/core/src/mindustry/content/TechTree.java#L97).
